### PR TITLE
Bump dependencies to resolve high vulnerabilities

### PR DESCRIPTION
**Pull request by davidfurey**
## What does this change?

Bumps a few dependencies and makes a minor change to squash deprecation warning.

The tests still pass, but I need to deploy to code to check that snapshotting still works as expected.

### CODE REVIEW

**Review by Fweddi — COMMENTED** [review]
Have deployed to CODE and tested by publishing an article in Composer. There was no snapshot in Restorer - and some errors in the logs: https://logs.gutools.co.uk/s/editorial-tools/app/r/s/pn1Ti.

**Comment by davidfurey** [comment]
Sorry, I should have added a note to this PR - I noticed this morning that this requires a change in editorial-tools-platform too: https://github.com/guardian/editorial-tools-platform/pull/830

**Comment by davidfurey** [comment]
Tested on CODE - snapshots appearing in composer now and no errors in logs. @Fweddi can you re-review?

**Review by Fweddi — APPROVED** [review]

**Comment by davidfurey** [comment]
Deployed to PROD, triggered and scheduled snapshots are still created. But logging seems to be broken, so I'm investigating that now.

**Comment by davidfurey** [comment]
Logging fixed by https://github.com/guardian/flexible-snapshotter/pull/42

**Pull request merged**
